---
# This playbook contains common plays that will be run on all nodes.

- name: xvfb | Install xvfb package
  apt: pkg={{ item }} state=present update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'  
  tags: package  
  with_items:
   - xvfb
      
- name: xvfb | Copy the xvfb init script
  copy: src=xvfb-{{ ansible_distribution }}.sh dest=/etc/init.d/xvfb mode=0755
  when: (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  tags: configure
  
- name: xvfb | Start the xvfb service
  service: name=xvfb state=started enabled=true
  tags: service  
        
